name:                yamemo
version:             0.6.1.0
github:              nobsun/yamemo
license:             BSD3
author:              Nobuo Yamashita
maintainer:          nobsun@sampou.org
copyright:           © 2025, Nobuo Yamashita

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/yamemo#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- time
- hspec
- main-tester
- doctest
- array
- containers
- mtl
- free
- recursion-schemes
- vector

language: GHC2021

default-extensions:
- ImplicitParams
- ImportQualifiedPost
- LambdaCase
- LexicalNegation
- MultiWayIf
- NPlusKPatterns
- OverloadedStrings
- DataKinds
- PolyKinds
- NoStarIsType
- TypeFamilyDependencies
- UndecidableInstances

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors
- -Wno-unused-imports
- -Wno-unused-top-binds
- -Wno-orphans

library:
  source-dirs: src

executables:
  fib:
    main:               Main.hs
    source-dirs:        app/fib
    ghc-options:
    - -rtsopts
    dependencies:
    - yamemo

  cc:
    main:               Main.hs
    source-dirs:        app/cc
    ghc-options:
    - -rtsopts
    dependencies:
    - yamemo

  yamemo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - yamemo

tests:
  yamemo-test:
    main:                spec.hs
    source-dirs:         test
    dependencies:
    - yamemo
    - hspec
    - main-tester

  yamemo-doctest:
    main:                doctests.hs
    source-dirs:         test
    dependencies:
    - yamemo
    - doctest
